name: Build NeuroTumAI

on:
  push:
    branches: [ main ]
  workflow_dispatch:

env:
  DOTNET_VERSION: '8.0.x'
  PUBLISH_PATH: 'publish'

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}
    
    - name: Restore
      run: dotnet restore ./NeuroTumAI.APIs-N/NeuroTumAI.Solution.sln
      
    - name: Build
      run: dotnet build ./NeuroTumAI.APIs-N/NeuroTumAI.Solution.sln --configuration Release --no-restore
      
    - name: Publish
      run: dotnet publish ./NeuroTumAI.APIs-N/NeuroTumAI.APIs/NeuroTumAI.APIs.csproj -c Release -o ${{env.PUBLISH_PATH}}
    
    - name: Upload Build Artifact
      uses: actions/upload-artifact@v4
      with:
        name: neurotumai-build
        path: ${{ env.PUBLISH_PATH }}